Added Pet related entities
IF-125/VetClinic.Backend pull request #17
Opened 2021-06-28 12:53 UTC by kaboo21

Approximate time spent: 2 hours

2021-06-30 12:09 UTC, Serafinium commented on VetClinic.DAL/Configurations/PetEntityConfiguration.cs
> +
please drop redundant space

2021-06-30 12:11 UTC, Serafinium commented on VetClinic.Core/Entities/PetImages.cs
> +    public class PetImages
Please add Fluent API Configurations

2021-07-11 10:13 UTC, Serge1212 requested changes

2021-07-11 10:13 UTC, Serge1212 commented on VetClinic.BLL/Services/PetServise.cs
> +    public class PetServise:IPetService
add spaces (PetServise : IPetService)

2021-07-11 10:13 UTC, Serge1212 commented on VetClinic.Host/Startup.cs
> +            services.AddScoped<IPetService, PetServise>();
Pay attention for namings: ~~PetServise~~ -> PetService

2021-07-11 10:13 UTC, Serge1212 commented on VetClinic.WebApi/Controllers/PetsController.cs
> +}
Do not use DbContext in controllers, user services instead

2021-07-11 10:13 UTC, Serge1212 commented on VetClinic.DAL/Context/VetClinicDbContext.cs
> +            Database.EnsureCreated();
Remove this

2021-07-11 10:13 UTC, Serge1212 commented on VetClinic.Core/Interfaces/Services/IPetService.cs
> +    }
IPetService must be inherited from IBaseService

2021-07-14 12:18 UTC, merged